[package]
name = "newsapi"
version = "0.1.0"
authors = ["biomunky <biomunky@gmail.com>"]
edition = "2018"

[lib]   
name="newsapi"
path="src/lib.rs"

[dependencies]
lazy_static = "1.3"
chrono = {version = "0.4", features = ["serde"]}
reqwest = "0.9"
custom_error = "1.6.0"

