[package]
name = "newsapi"
version = "0.1.0"
authors = ["biomunky", "lotia"]
edition = "2018"
homepage = "https://github.com/biomunky/newsapi"
description = "Wrapper for the newsapi, uses reqwest to do the http work. A learn by doing project"
keywords = ["newsapi", "client"]
license = "MIT/Apache-2.0"
readme = "README.md"
categories = ["api-bindings"]

[lib]
name="newsapi"
path="src/lib.rs"

[dependencies]
lazy_static = "1.3"
chrono = {version = "0.4", features = ["serde"]}
reqwest = "0.9"
custom_error = "1.6.0"
percent-encoding = "1.0"
url = "1.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
enum-map = "0.5"
